import Image from "next/image";
import Link from "next/link";

const solutions = [
  { n: "01", title: "Marine & cargo", text: "Responsive protection for cargo in transit, marine operations and connected supply-chain exposures." },
  { n: "02", title: "Financial guarantee", text: "Purpose-built assurance structures supporting contractual, project and financing obligations." },
  { n: "03", title: "Indemnity & liability", text: "Specialist protection aligned to professional, contractual and operational responsibilities." },
  { n: "04", title: "Specialty risk", text: "Bespoke risk transfer for complex exposures that require experienced, case-specific analysis." },
];

const sectors = [["Global trade", "Cargo owners, distributors and cross-border supply chains"], ["Marine", "Vessel interests, logistics operators and maritime services"], ["Infrastructure", "Project obligations and commercial performance risks"], ["Financial services", "Credit, contractual and professional exposures"]];

export default function Home() {
  return <><section className="hero"><Image src="/hero.webp" alt="Container vessel approaching an international port at sunrise" fill priority sizes="100vw" /><div className="hero-shade" /><div className="container hero-content"><p className="eyebrow light">Specialty insurance · Global trade</p><h1>Confidence across<br />every crossing.</h1><p className="hero-copy">Sino Secure brings disciplined underwriting and connected international expertise to marine, financial and specialty risks.</p><div className="hero-actions"><Link className="button" href="/contact">Request underwriting <span>↗</span></Link><Link className="text-link light" href="#solutions">View solutions <span>↓</span></Link></div></div><div className="hero-proof"><span>Australia based</span><span>Cross-border reach</span><span>Case-led underwriting</span></div></section>
  <section className="intro section" id="about"><div className="container split-intro"><div><p className="eyebrow">Risk, understood</p><h2>Protection designed around how business actually moves.</h2></div><div><p className="lead">Complex trade and specialty exposures need more than a standard product list.</p><p>We begin with the transaction, route, obligation or operational reality—then work with specialist partners to shape a credible response.</p><Link className="text-link" href="/contact">Open an underwriting conversation <span>↗</span></Link></div></div></section>
  <section className="section section-ink" id="solutions"><div className="container"><div className="section-heading inverse"><p className="eyebrow light">Solutions</p><h2>Specialty cover with commercial context.</h2><p>Clear thinking, coordinated capacity and terms that reflect the real exposure.</p></div><div className="capability-grid">{solutions.map((item)=><article key={item.n}><span>{item.n}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
  <section className="section" id="sectors"><div className="container"><div className="section-heading"><p className="eyebrow">Sectors</p><h2>Built around movement, obligation and enterprise value.</h2></div><div className="portfolio-list">{sectors.map(([name,text],i)=><article key={name}><span>0{i+1}</span><h3>{name}</h3><p>{text}</p><small>Specialty</small></article>)}</div></div></section>
  <section className="section portfolio-section" id="network"><div className="container split-intro"><div><p className="eyebrow">Global network</p><h2>Local perspective. Connected placement.</h2></div><div><p className="lead">Sino Secure works across a network of insurance, reinsurance and professional-services relationships.</p><p>That network helps us coordinate territory-specific insight and specialist capacity without losing single-point accountability.</p><div className="contact-details"><p><strong>Australia</strong><br />Primary office</p><p><strong>Europe · Americas</strong><br />Connected regional expertise</p></div></div></div></section>
  <section className="cta-band"><div className="container"><p className="eyebrow light">Start with the exposure</p><h2>Tell us what moves, what is promised and what must be protected.</h2><Link className="button button-light" href="/contact">Request an underwriting response <span>↗</span></Link></div></section></>;
}
